# Generated by Django 6.0.4 on 2026-04-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_seed', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_log_status_9e3e25_idx',
            old_name='email_log_status_c8e8e5_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_log_recipie_d43226_idx',
            old_name='email_log_recipie_8f9a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_log_task_id_2a1ea1_idx',
            old_name='email_log_task_id_4a5b2d_idx',
        ),
    ]
